In [2]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [5]:
df = pd.read_csv('heart.csv')


In [6]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2, random_state=2)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [11]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

/nfs/cms/mtech23/lute.gaurav/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [12]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy of Logistic Regression", accuracy_score(y_test, y_pred1))
print('Accuracy of Decision Trees',accuracy_score(y_test, y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Trees 0.819672131147541


In [14]:
confusion_matrix(y_test, y_pred1)

array([[26,  6],
       [ 0, 29]])

In [15]:
print('Logistic Regression Confusion Matrix\n')
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  26   6
1   0  29

In [16]:
print('Decision Tree Confusion Matrix\n')
pd.DataFrame(confusion_matrix(y_test, y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  24   8
1   3  26

In [18]:
result=pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction']=y_pred1
result['Decision Tree Prediction']=y_pred2

In [19]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
192             0                               0                         0
7               1                               1                         1
112             1                               1                         1
142             1                               1                         0
89              1                               1                         1
231             0                               0                         0
35              1                               1                         1
134             1                               1                         1
250             0                               0                         0
99              1                               1                         1

In [20]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [21]:
print('For Logistic regression Model')
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print('Precision -',precision_score(y_test, y_pred1))
print('Recall -',recall_score(y_test, y_pred1))
print('F1 score -',f1_score(y_test, y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision - 0.8285714285714286
Recall - 1.0
F1 score - 0.90625


In [23]:
print('For Decission Tree model')
print('-'*50)
cdf = pd.DataFrame(confusion_matrix(y_test, y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision -", precision_score(y_test, y_pred2))
print('Recall -',recall_score(y_test, y_pred2))
print('F1 score -', f1_score(y_test, y_pred2))

For Decission Tree model
--------------------------------------------------
    0   1
0  24   8
1   3  26
--------------------------------------------------
Precision - 0.7647058823529411
Recall - 0.896551724137931
F1 score - 0.8253968253968254


In [25]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [26]:
precision_score(y_test, y_pred2, average = None)

array([0.88888889, 0.76470588])

In [27]:
recall_score(y_test, y_pred2, average=None)

array([0.75      , 0.89655172])